### ISSUE TITLE
Card Cover Bank

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOSalvation-Server#290]
Using DB System have a HTTP based put system that uses verification. On Launcher startup it sends images as a data URI to the server. The server stores them as http accessible images.
- [ ] Setup Microservice
- [ ] HTTP POST entry
- [ ] Verifies USERNAME and PASSWORD against the forum
- [ ]  After x tries block the IP.
- [ ] Converts the URI to a buffer
- [ ] Stores the buffer to file with that USERNAME to HTTP Accessible location
- [ ] `.jpg` files in location should be ignored in git.

**Comment by Zayelion** [comment]
Needs to be reworked to work with Manual

**Comment by Hello23-Ygopro** [comment]
Will both players be able to see each others Card Covers ? That would be nice to have
i dont think any Ygopro supports that currently unless you donate or something.. 
I also think there should be measures to stop people from uploading offensive images , but i have no idea how that would work .. like some image verifcation tool , idk.. and users could always report those people

**Comment by Zayelion** [comment]
Moving to the admin project
