### ISSUE TITLE
Manual Mode Beta Pre-Release Issues

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOSalvation-Server#302]
## Missing Features
- [ ] Spectate in progress duels
- [x] Ability to kick players from games you're hosting
- [x] Unlock Deck after lock.
- [x] Missing counts for Main Deck, Extra Deck, Graveyard, Banished
- [x] Kick button
- [x] Attack Directly Option
- [x] Field Spell Background

## Known Bugs
- [x] Avatars overlap side controls on wide screen.
- [x] In some browsers face down cards do not show correctly.
- [x] Attack button plays special summon sound
- [ ] Perfectly stable internet connection is required.
- [x] Sorting in deck edit is inconsistent.
- [x] Scaling of the game field is improper at certain resolutions resulting in it being small overall.
- [x] Spectators have to surrender to leave
- [x] Activating a Spell/Trap from Deck does not move the card properly.
- [x] Link Monsters return to hand instead of the Extra Deck
- [x] Firefox users cannot see their cards flip facedown
- [x] Xyz Summoning in the Extra Deck Monster Zone is awkward

**Comment by Hello23-Ygopro** [comment]
I wish i found this sooner.. thanks for working on a manual mode ,
especially when its browser-based , and not just limited to Chrome 😂

### Features
Each Ygopro has something unique to them , and something like this will definitely draw alot more people to Salvation , also cus theres a alot of people who prefer manual-based gameplay to help prepare better for events

I also agree with adding this feature : `Spectators have to surrender to leave`
Thats a growing problem in the Ygopro community : rage-quitting but not just that , people quitting their application or even shutting off their router to prevent a replay from being saved
No feature can stop that from happening but that should lessen it , you can also argue that it could keep people away , but i think the majority in the community dont like constant quitting
#
Edit : i forgot where , but i also remember reading somewhere that the face-down Attack Position button or an option for that would be omitted
Personally , i hope not even if its only supported by Darkness Approaches

**Comment by StormWulf** [comment]
# Buttons that shouldn't exist
- Remove `Move to Monster Zone` button for Trap Monster cards
- Remove `Excavate` button from hand cards
- Remove `Activate` button from Field spells

# Other feedback
- Server messages should be thicker 
- Left-clicking on an area should remove card menus
- Empty space needs to be optimized
- Left-side buttons interfere with the graveyard for resolution 1280 x 1024 (http://prnt.sc/er0tsh)
- Excavated cards should be face-up

**Comment by Zayelion** [comment]
All known bugs have been fixed in previous releases but manual has to be re implemented.
