### ISSUE TITLE
Dueling Book comparison

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOSalvation-Server#325]
# Features unique to Dueling Book
- Colorful GUI  
- RPS system  
- Only the active player can control the phases  
- ~~Attacking is bound to Battle Phase~~
- **In-game logs viewable to users.**  ![Pastebin example](https://pastebin.com/esQrAXcH)  
![Duel Log visual example](http://image.prntscr.com/image/f365df001ebc4b3790e261e0494d75f1.png)  
- Watcher's chat
- Viewing deck only covers the opponent's field, and it doesn't close automatically after moving a card. ![Deck View](http://image.prntscr.com/image/541802c3a14e4f8499e5568698ada6b8.png)  
- Deck is automatically shuffled after closing the View Deck, no animation.  
- Dice, coin, and LP change buttons for user-convenience.  
- Manual zone selection is a toggle option  
- Playable on weak internet connection  
- Game list filtering  
- Deck Edit includes counts for each card type (Monster, Spell, Trap, Extra Deck)
- Import option accepts XML formatting  
- Export option allows YDK, XML, and KDE deck list formatting  

# What they don't have
- Support for obscure cards (Convulsions of Nature, Exchange, etc)  
- Multiple banlist support  
- Prerelease cards  
- Multiple tokens besides Sheep Tokens
- Completely inaccessible by mobile due to Flash

**Comment by Zayelion** [comment]
Attacking is bound to the attack phase in Salvation.

**Comment by Zayelion** [comment]
- https://github.com/SalvationDevelopment/YGOPro-Salvation-Server/commit/8331739ff965410bf3af629d3d43868be68b7fb2 : Made some changes so the DB loads faster on weak internet connections. On high speed connections the Deck Edit loading screen shouldnt even appear.
- Reworked deck editor to work partly on some mobile devices

**Comment by Zayelion** [comment]
- Added counts for each card type (Monster, Spell, Trap, Extra Deck) in deck edit.
