### ISSUE TITLE
Feedback notes for Manual Mode

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOSalvation-Server#327]
# Buttons that shouldn't exist
- [ ] Remove `Move to Monster Zone` button for Trap Monster cards
- [ ] Remove `Excavate` button from hand cards
- [ ] Remove `Activate`, `To Defense` button from Field spells

# Missing buttons
- [ ] Artifact cards and such are missing a `Set to S/T` button

# Other feedback
- [ ] Server messages should be thicker 
- [x] Left-clicking on an area should remove card menus
- [ ] Empty space needs to be optimized
- [x] Left-side buttons interfere with the graveyard for resolution 1280 x 1024 (http://prnt.sc/er0tsh)
- [ ] Excavated cards should be face-up
- [ ] Door bell sound when a player locks a deck, or some other alert

**Comment by Zayelion** [comment]
"Excavate" is a spare zone, it allows more cards to be implemented, its not a real zone. Left-side buttons rework is being planned, its been a low priority. 

- [ ] Camera options need to be worked into their own ara
- [ ] other buttons need to be moved else where maybe.

**Comment by Zayelion** [comment]
Made it so moving away from the menu causes it to close.
