### ISSUE TITLE
Xyz Summon procedure

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOSalvation-Server#329]
This procedure needs polishing, and Dueling Book's implementation sets a good example  

- [ ] Cards overlaid together should move together with the `Move` button
- [x] The user shouldn't be allowed to use the `Move` button to place a card in an occupied zone
- [ ] The `overlay` button needs to prioritize Xyz Monsters placed latest on the index. Sometimes when a user summons `Number S39: Utopia the Lightning`, the regular `Number 39: Utopia` still shows on top of the stack.
- [ ] The `overlay` button should place both cards vertically before stacking them
- [ ] The `View` button should only show for stacks

**Comment by Zayelion** [comment]
https://github.com/SalvationDevelopment/YGOPro-Salvation-Server/commit/6539fc7 : Users can no long move cards to occupied zones.

**Comment by StormWulf** [comment]
I was still able to move a card to the same zone as another card

**Comment by Zayelion** [comment]
Steps to reproduce?

**Comment by StormWulf** [comment]
![Step 1](http://image.prntscr.com/image/7a6fc64b037f4cf5a18f6e706eadba36.png)
![Step 2](http://image.prntscr.com/image/780979c01c3f449a94e673ce9c6328b8.png)
![Step 3](http://image.prntscr.com/image/194f5494966249d1b60b0356b1256e27.png)
![Step 4](http://image.prntscr.com/image/9f4aacb64f824b599901eb5168f00225.png)
