### ISSUE TITLE
`View Opponent's Extra Deck` feature is wacky

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOSalvation-Server#355]
When you click on your opponent's Extra Deck, the `View Extra Deck` button appears out of place, and you wouldn't be able to click it because it's so far from the zone.

![View Opponent Extra Deck button misplacement](https://puu.sh/wk4TL/f0d66f7c65.png)

We also need to confirm that it works. Face-Up Pendulum Monsters should definitely be visible to the other player, and everything else should appear as a face-down card.

**Comment by Zayelion** [comment]
This happens because the code either breaks along the execution of the onclick, or the re position is not called.
