### ISSUE TITLE
Image Templating System

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOSalvation-Server#362]
**Purpose**  
I'm sure that everyone on staff understand how tedious it is to generate card pictures, especially in bulk. My Python tool can generate the Japanese card proxies in the proper dimensions of 177 x 254, but we need these to be in English, as that's the standard for Yugioh simulators. With a template system, generating English card images can be an automatic process, and would be especially helpful for bulk operations. With this, it would also be easy to update outdated card text.  

**How would someone be able to use such a thing**  
In my mind, a user would just need to supply the card IDs or card names as an input. Then, the system would loop through each to generate a card image. Finally, the user would just need to commit them via GitHub.  

**How to implement**  
- Need to have all of the different card layers available (especially for Link Monsters, which aren't supported by TCGEditor)  
- The system could determine the card layer based on the card's database information, as well as stats and card description
- Need to determine the dimensions to crop out a card picture from the border (assuming that it's the same for all cards at 177 x 254 dimensions) so that it can be placed inside the card layer

**Comment by Zayelion** [comment]
Abandoning this for now, images are now provided by users.
