### ISSUE TITLE
Link Arrow search filter

### ISSUE THREAD

**Issue by StormWulf** [SalvationDevelopment/YGOSalvation-Server#363]
I would like to create a search filter similar to the one used by Konami's official database (https://www.db.yugioh-card.com/yugiohdb/card_search.action). You would have to view the site with the Japanese language to use it properly since there are no Link Monsters currently legal in the TCG.  

Here's how I feel it should work:  
- Have the Link Arrow selection appear similar to how it does on Konami DB, and selecting `Link Monster` for the Monster typing dropdown could reveal it
- For every arrow selected, the search filter can append `and desc like "%🡱%"` for the case of clicking the Top arrow or `and desc like "%🡷%"` for the Bottom-Left arrow when querying the database. All Link Monsters have these unicode symbols, making this particular task relatively easy.

The UI uses the most amount of space when the `Monster` Card Category is selected, and there's `980` pixels of height available. The amount of space would only require a height of `550` pixels.  

![Konami DB Link Arrows](https://puu.sh/wqCJb/253d21dbe1.png)

**Comment by Zayelion** [comment]
Completed
